### ISSUE TITLE
Add release-related rules and GitHub Actions workflow

### ISSUE THREAD

**Issue by cgrindel** [keith/buildifier-prebuilt#11]
I implemented some Bazel rules ([bzlrelease](https://github.com/cgrindel/bazel-starlib/tree/main/bzlrelease)) that work with a GitHub Actions workflow to create releases for my Bazel rule repositories. In short, it generates the release notes along with a workspace snippet, creates the GitHub release, and creates an auto-merge PR to update the `README.md` with the latest workspace snippet.

All of the pre-requisites are already being loaded in this repository. I would add a `release` Bazel package that would contain a `BUILD` file, `README.md` file, and a workspace snippet template (i.e., contains the load statements that need to be added to client workspaces). I would update the repository's `README.md` to include two markers as markdown comments to indicate where to insert/replace the generated workspace snippet. Releases can be created using a Bazel run command or via [the GitHub Actions web interface](https://github.com/keith/buildifier-prebuilt/actions).

If you would like to see an actual implementation, here is [the release package](https://github.com/cgrindel/bazel-starlib/tree/main/release), [the GitHub Actions workflow](https://github.com/cgrindel/bazel-starlib/blob/main/.github/workflows/create_release.yml) and [a release generated by this process](https://github.com/cgrindel/bazel-starlib/releases/tag/v0.3.2) for `cgrindel/bazel-starlib`. I could add this pretty quickly if you are interested.

**Comment by keith** [comment]
sounds nice to me!
