### ISSUE TITLE
Create release 0.1.4 or 0.2.0

### ISSUE THREAD

**Issue by cgrindel** [keith/buildifier-prebuilt#15]
I think that we are ready to create a release with the new code. Would you like to do the honors? I am happy to kick it off. I just need to know what version number you would like to use.

**Comment by keith** [comment]
Seems like 0.2.0 is appropriate, go for it!

**Comment by cgrindel** [comment]
@keith Looks like the release worked. Woohoo! 🎉

**Comment by keith** [comment]
Epic! Thanks for all the hard work here!
