### ISSUE TITLE
Add buildifier_test

### ISSUE THREAD

**Issue by erikkerber** [keith/buildifier-prebuilt#40]
The rule here has diverged a bit from [buildtools](https://github.com/bazelbuild/buildtools/blob/master/buildifier/internal/factory.bzl), namely that buildtools wraps the "diff" mode in a test rule useful for CI checks

https://github.com/bazelbuild/buildtools/blob/master/buildifier/buildifier.bzl#L37-L41

I was going to adopt this prebuilt strategy and clean up our WORKSPACE a bit, but hit a snag in that small difference.

Checking here if matching the rules in the buildtools source is a goal, and if so I'll open a patch.

**Comment by keith** [comment]
Yea I think having similar rules to that repo would be good. I can't recall but I think I omitted that one since it doesn't seem super common to use these days because of the inability to glob files.

**Comment by keith** [comment]
Included in 5.1.0.1, thanks!
