### ISSUE TITLE
buildifier rule does not build on windows

### ISSUE THREAD

**Issue by jbedard** [keith/buildifier-prebuilt#68]
Due to no windows toolchain existing? I think it should at least build even if it fails to run, otherwise it must be marked as `manual` to avoid even building it by default (but then it's of course manual for all platforms).

Ideally something such as `target_compatible_with` should be used, however that doesn't stop the toolchains from being downloaded so won't work with the usage of toolchains like today (6.1.0).

**Comment by keith** [comment]
I don't have a windows machine to test with but definitely happy to take PRs to make this nicer

**Comment by jbedard** [comment]
For now I've just tagged it as manual and probably won't put anymore time into it right now. If the issue comes up again maybe I'll give it a shot 👍

**Comment by alexeagle** [comment]
If the Bazel team would just give any rule author a Windows VM on GCP that works - half of the Bazel windows problems might get solved 😓
